// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg7rQ9P8Akb8SMxPjQvtJcVwCR25qlbgw',
    appId: '1:818015549149:web:48f716e99bd920910ecd34',
    messagingSenderId: '818015549149',
    projectId: 'totem-dev-184f1',
    authDomain: 'totem-dev-184f1.firebaseapp.com',
    storageBucket: 'totem-dev-184f1.appspot.com',
    measurementId: 'G-9K7JNBDEFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsPEU7nB4lBzC-v4emBNtYaP-lwlVVRA0',
    appId: '1:818015549149:android:1255de9069b1aac80ecd34',
    messagingSenderId: '818015549149',
    projectId: 'totem-dev-184f1',
    storageBucket: 'totem-dev-184f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZGg-Bu9kalJ1cDgE60jvCwHMJSRcIZTQ',
    appId: '1:818015549149:ios:03f63a8e2314ad6a0ecd34',
    messagingSenderId: '818015549149',
    projectId: 'totem-dev-184f1',
    storageBucket: 'totem-dev-184f1.appspot.com',
    iosClientId:
        '818015549149-sftthv337pum4h4l6ba69hnpsenvb9fp.apps.googleusercontent.com',
    iosBundleId: 'io.kbl.totem.dev',
  );
}
