# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
opt_out_usage

platform :ios do
  desc "Create signed release build"
  lane :build do
    setup_ci if is_ci
    match(type: 'appstore')
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/Runner.xcodeproj"
    )
    sh("flutter build ipa")
    build_app(scheme: "Runner",
      workspace: "ios/Runner.xcworkspace",
      export_method: "app-store",
      output_name: "totem.ipa",
      skip_build_archive: true,
      skip_package_dependencies_resolution: true,
      archive_path: "build/ios/archive/Runner.xcarchive"
    )
  end
  desc "Push to internal TestFlight users"
  lane :internal do
    if is_ci
      setup_ci
      app_store_connect_api_key(
        key_id: "V8G6QL36D2",
        issuer_id: "23440d74-86b4-4a09-9225-d22cf0a2607a",
        key_content: ENV["APPLE_STORE_CONNECT_API_KEY"]
      )
    end
    # upload_to_testflight
  end
end
