# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
require 'json'
opt_out_usage

# iOS lanes
platform :ios do
  desc "Create signed release build"
  lane :build do
    setup_ci if is_ci
    match(type: 'appstore')
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/Runner.xcodeproj"
    )
    sh("flutter build ipa")
    build_app(scheme: "Runner",
      workspace: "ios/Runner.xcworkspace",
      export_method: "app-store",
      output_name: "totem.ipa",
      skip_build_archive: true,
      skip_package_dependencies_resolution: true,
      archive_path: "build/ios/archive/Runner.xcarchive"
    )
  end
  desc "Push to internal TestFlight users"
  lane :internal do
    if is_ci
      setup_ci
      app_store_connect_api_key(
        key_id: "V8G6QL36D2",
        issuer_id: "23440d74-86b4-4a09-9225-d22cf0a2607a",
        key_content: ENV["APPLE_STORE_CONNECT_API_KEY"]
      )
    end
    # upload_to_testflight
  end
end


# Android lanes
platform :android do
  desc "Submit a new Build to the Google Play internal test track"
  lane :internal do
    puts "hi"
    if is_ci
      key_data = ENV["PLAY_DEPLOY_KEY"]
    else
      key_data = IO.read("../play-deploy-key.json")
    end
    # upload_to_play_store(track: 'internal', json_key_data: key_data, aab: "build/app/outputs/bundle/release/app-release.aab")
  end
end
